---
blueprint:
  name: Advanced Occupancy Light Control
  description: >-
    A comprehensive motion/occupancy-activated control blueprint for lights,
    switches, fans, and more. Turns on entities when occupancy is detected
    and turns them off after a delay. Includes advanced, optional conditions
    for sun position and fixed time ranges.
    Based on blueprints by @Aleks130699, @iainsmacleod, and @home-assistant.
  author: DracoArgenteus
  homeassistant:
    min_version: "2024.6.0"
  source_url: >-
    https://github.com/DracoArgenteus/automations/heads/main/advanced_occupancy_automation.yaml
  domain: automation
  input:
    occupancy_sensor:
      name: Occupancy Sensor(s)
      description: >-
        The binary sensor(s) that detect presence. The automation will
        trigger if any turn on, and wait for all to turn off.
      selector:
        entity:
          domain: binary_sensor
          multiple: true
          device_class:
            - motion
            - occupancy
            - presence

    target_entity:
      name: Target Entity
      description: The entity or entities to control (e.g., light, switch, fan).
      selector:
        target:
          entity:
            domain:
              - light
              - switch
              - fan
              - input_boolean

    turn_off_delay:
      name: Turn-off delay
      description: >-
        Time to wait before turning off the entity after all occupancy sensors
        are clear.
      default: 90
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

    # --- Conditions ---
    condition_type:
      name: Condition Type
      description: What condition must be met for the entities to turn on.
      default: "none"
      selector:
        select:
          options:
            - label: "Always On"
              value: "none"
            - label: "Sun Position"
              value: "sun"
            - label: "Fixed Time Range"
              value: "time"

    sun_condition_mode:
      name: Sun Condition (if type is Sun)
      description: >-
        Turn on the entity only when the sun is above or below the horizon.
      default: "below_horizon"
      selector:
        select:
          options:
            - "below_horizon"
            - "above_horizon"

    sunset_offset:
      name: Sunset Offset (for Sun condition)
      description: >-
        Optional offset to start the 'below horizon' period earlier (e.g.,
        '00:30:00' to start 30 mins before sunset).
      # default: "00:00:00"
      default: ""
      selector:
        time:

    sunrise_offset:
      name: Sunrise Offset (for Sun condition)
      description: >-
        Optional offset to end the 'below horizon' period later (e.g.,
        '00:30:00' to end 30 mins after sunrise).
      default: ""
      selector:
        time:

    time_start:
      name: "Time: Start (for Time condition)"
      description: "Time to start turning the entity on (e.g. 18:00:00)."
      default: ""
      selector:
        time:

    time_end:
      name: "Time: End (for Time condition)"
      description: "Time to stop turning the entity on (e.g. 06:00:00)."
      default: ""
      selector:
        time:

    # --- Light Settings (only apply to light entities) ---
    brightness_pct:
      name: Brightness
      description: >-
        (Optional, Lights Only) The brightness of the light (0-100). Leave
        blank to use the light's last state.
      default:
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

    color_temp:
      name: Color Temperature (Kelvin)
      description: >-
        (Optional, Lights Only) Color temperature in Kelvin. Overrides RGB
        Color if set.
      default:
      selector:
        number:
          min: 2000
          max: 6500
          step: 100
          unit_of_measurement: "K"

    rgb_color:
      name: RGB Color
      description: >-
        (Optional, Lights Only) The RGB color for the light. Is overridden
        by Color Temperature if set.
      default:
      selector:
        color_rgb:

mode: restart

variables:
  occupancy_entities: !input occupancy_sensor
  target_entity: !input target_entity
  condition_type: !input condition_type
  sun_condition_mode: !input sun_condition_mode
  sunset_offset: !input sunset_offset
  sunrise_offset: !input sunrise_offset
  time_start: !input time_start
  time_end: !input time_end
  brightness_pct: !input brightness_pct
  color_temp: !input color_temp
  rgb_color: !input rgb_color

trigger:
  - platform: state
    entity_id: !input occupancy_sensor
    from: "off"
    to: "on"

condition:
  - condition: template
    value_template: >
      {% if condition_type == 'sun' %}
        {% if sun_condition_mode == 'above_horizon' %}
          {{ is_state('sun.sun', 'above_horizon') }}
        {% else %}
          {% set sunset = state_attr('sun.sun', 'next_setting') | as_datetime | as_local %}
          {% set sunrise = state_attr('sun.sun', 'next_rising') | as_datetime | as_local %}
          {% set sunset_offset_delta = timedelta(hours=sunset_offset.split(':')[0]|int, minutes=sunset_offset.split(':')[1]|int) %}
          {% set sunrise_offset_delta = timedelta(hours=sunrise_offset.split(':')[0]|int, minutes=sunrise_offset.split(':')[1]|int) %}
          {{ now() >= (sunset - sunset_offset_delta) or now() <= (sunrise + sunrise_offset_delta) }}
        {% endif %}
      {% elif condition_type == 'time' %}
        {% if time_start and time_end %}
          {% set time_now = now() %}
          {% set time_start_obj = today_at(time_start) %}
          {% set time_end_obj = today_at(time_end) %}
          {% if time_start_obj < time_end_obj %}
            {{ time_start_obj <= time_now < time_end_obj }}
          {% else %}
            {{ time_now >= time_start_obj or time_now < time_end_obj }}
          {% endif %}
        {% else %}
          true
        {% endif %}
      {% else %}
        true
      {% endif %}

action:
  - service: homeassistant.turn_on
    target: !input target_entity
    data: >
      {% set data = {} %}
      {% if brightness_pct is defined and brightness_pct not in [none, ''] %}
        {% set _ = data.update({'brightness_pct': brightness_pct}) %}
      {% endif %}
      {% if color_temp is defined and color_temp not in [none, ''] %}
        {% set _ = data.update({'kelvin': color_temp}) %}
      {% elif rgb_color is defined and rgb_color not in [none, ''] %}
        {% set _ = data.update({'rgb_color': rgb_color}) %}
      {% endif %}
      {{ data }}

  - wait_template: >-
      {{ expand(occupancy_entities) | selectattr('state', 'eq', 'off') | list
      | count == expand(occupancy_entities) | list | count }}

  - delay:
      seconds: !input turn_off_delay

  - service: homeassistant.turn_off
    target: !input target_entity
